# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: maven
    directory: /
    exclude-paths:
      - "releng/target-platform"
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: maven
    directories:
      - "releng/target-platform"
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      org-bouncycastle:
        applies-to: version-updates
        patterns:
          - 'org.bouncycastle:*'
        update-types:
          - 'minor'
          - 'patch'
      org-slf4j:
        applies-to: version-updates
        patterns:
          - 'org.slf4j:*'
        update-types:
          - 'minor'
          - 'patch'
      ch-qos-logback:
        applies-to: version-updates
        patterns:
          - 'ch.qos.logback:*'
        update-types:
          - 'minor'
          - 'patch'
      com-fasterxml-jackson:
        applies-to: version-updates
        patterns:
          - 'com.fasterxml.jackson*:*'
          - 'org.yaml:*'
          - 'stax2-api:*'
          - 'woodstox-core:*'
        update-types:
          - 'minor'
          - 'patch'
      io-netty:
        applies-to: version-updates
        patterns:
          - 'io.netty:*'
        update-types:
          - 'patch'
      io-swagger-core:
        applies-to: version-updates
        patterns:
          - 'io.swagger.core.v3:*'
        update-types:
          - 'minor'
          - 'patch'
      org-eclipse-jetty:
        applies-to: version-updates
        patterns:
          - 'org.eclipse.jetty*:*'
        update-types:
          - 'minor'
          - 'patch'
      org-ow2-asm:
        applies-to: version-updates
        patterns:
          - 'org.ow2.asm:*'
        update-types:
          - 'minor'
          - 'patch'
      io-rest-assured:
        applies-to: version-updates
        patterns:
          - 'io.rest-assured:*'
        update-types:
          - 'minor'
          - 'patch'
      net-bytebuddy:
        applies-to: version-updates
        patterns:
          - 'net.bytebuddy:*'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: '10.x'