<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>com.b2international.snowowl.server.update</artifactId>
	<packaging>eclipse-repository</packaging>

	<parent>
		<groupId>com.b2international.snowowl</groupId>
		<artifactId>releng-parent</artifactId>
		<version>10.1.1-SNAPSHOT</version>
	</parent>
	
	<properties>
		<packageFiles>${project.build.directory}/${project.build.finalName}-oss/${project.build.finalName}</packageFiles>
		<product.rootFolder>snow-owl-oss-${build.version}</product.rootFolder>
		<products.directory>${project.build.directory}/products</products.directory>
		<product.id>com.b2international.snowowl.server</product.id>
		<so.products.directory>${products.directory}/${product.id}</so.products.directory>
		<linux.product.path>${so.products.directory}/linux/gtk/x86_64/${product.rootFolder}</linux.product.path>
		<win.product.path>${so.products.directory}/win32/win32/x86_64/${product.rootFolder}</win.product.path>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.semanticweb.elk</groupId>
			<artifactId>elk-protege</artifactId>
			<version>${elk.version}</version>
		</dependency>
	</dependencies>

	<build>
		<finalName>snow-owl-oss-${build.version}</finalName>
		<plugins>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-p2-director-plugin</artifactId>
				<executions>
					<execution>
						<id>materialize-products</id>
						<goals>
							<goal>materialize-products</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<products>
						<product>
							<id>${product.id}</id>
							<rootFolder>${product.rootFolder}</rootFolder>
						</product>
					</products>
				</configuration>
			</plugin>
			<!-- create site and server zip, tar.gz base folders -->
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<executions>
					<execution>
						<id>package-oss-unix</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
							<workDirectory>${project.build.directory}/assembly/oss</workDirectory>
							<descriptors>
								<descriptor>${basedir}/assembly/oss.xml</descriptor>
							</descriptors>
							<tarLongFileMode>gnu</tarLongFileMode>
						</configuration>
					</execution>
					<execution>
						<id>package-oss-win</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
							<workDirectory>${project.build.directory}/assembly/oss</workDirectory>
							<descriptors>
								<descriptor>${basedir}/assembly/oss-win.xml</descriptor>
							</descriptors>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>m2e</id>
			<!-- This profile is only activated when building in Eclipse with m2e -->
			<activation>
				<property>
					<name>m2e.version</name>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-resources-plugin</artifactId>
						<version>3.5.0</version>
						<executions>
							<execution>
								<id>copy-configuration-users</id>
								<phase>process-classes</phase>
								<goals>
									<goal>copy-resources</goal>
								</goals>
								<configuration>
									<resources>
										<resource>
											<directory>assembly/common/configuration</directory>
											<includes>
												<include>users</include>
												<include>snowowl.yml</include>
												<include>serviceability.xml</include>
												<include>jetty*.xml</include>
											</includes>
										</resource>
									</resources>
									<outputDirectory>${basedir}/runtime/configuration</outputDirectory>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>